# Generated by Django 5.2.6 on 2025-09-17 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PCBuild',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(max_length=100, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('office', 'Office'), ('editing', 'Editing/AI-ML'), ('gaming', 'Gaming')], max_length=20)),
                ('intensity', models.CharField(choices=[('casual', 'Casual'), ('heavy', 'Heavy')], max_length=20)),
                ('total_cost', models.PositiveIntegerField()),
                ('estimated_wattage', models.PositiveIntegerField()),
                ('compatibility', models.CharField(choices=[('optimized', 'Optimized'), ('warning', 'Warning')], max_length=20)),
                ('image_url', models.URLField(blank=True, null=True)),
                ('components', models.JSONField()),
                ('upgrades_suggestions', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['category', 'intensity', 'total_cost', 'name'],
            },
        ),
    ]
