# Generated by Django 5.2.5 on 2025-10-07 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0002_vendorbuild'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendorbuild',
            name='category',
            field=models.CharField(choices=[('gaming', 'Gaming'), ('office', 'Office'), ('workstation', 'Workstation')], default='gaming', max_length=20),
        ),
        migrations.AddField(
            model_name='vendorbuild',
            name='intensity',
            field=models.CharField(choices=[('casual', 'Casual'), ('moderate', 'Moderate'), ('intensive', 'Intensive')], default='casual', max_length=20),
        ),
        migrations.AddField(
            model_name='vendorbuild',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
