# Generated by Django 5.2.5 on 2025-10-14 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0003_vendorbuild_category_vendorbuild_intensity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendorbuild',
            name='case',
            field=models.CharField(default='Standard Casing', max_length=100),
        ),
        migrations.AddField(
            model_name='vendorbuild',
            name='psu',
            field=models.CharField(default='Standard PSU', max_length=100),
        ),
    ]
