# Generated by Django 5.2.5 on 2025-10-14 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0004_vendorbuild_casing_vendorbuild_psu'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendorbuild',
            name='case',
            field=models.CharField(default='Standard Casing', max_length=255),
        ),
    ]
