# Generated by Django 5.2.5 on 2026-01-27 12:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vendors', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Component',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('cpu', 'CPU'), ('gpu', 'GPU'), ('ram', 'RAM'), ('storage', 'Storage'), ('psu', 'Power Supply'), ('motherboard', 'Motherboard'), ('case', 'Case')], max_length=20)),
                ('name', models.CharField(max_length=150)),
                ('specs', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'unique_together': {('type', 'name', 'specs')},
            },
        ),
        migrations.CreateModel(
            name='Build',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('category', models.CharField(choices=[('office', 'Office / Study'), ('editing', 'Editing / AI-ML'), ('gaming', 'Gaming & Streaming')], default='office', max_length=20)),
                ('intensity', models.CharField(choices=[('casual', 'Casual'), ('heavy', 'Heavy')], default='casual', max_length=20)),
                ('source', models.CharField(choices=[('system', 'System Generated'), ('vendor', 'Vendor Provided')], default='system', max_length=20)),
                ('vendor_build_id', models.IntegerField(blank=True, db_index=True, help_text='Links to VendorBuild.id for sync tracking', null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('vendor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='provided_builds', to='vendors.vendor')),
                ('components', models.ManyToManyField(blank=True, to='builds.component')),
            ],
        ),
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchased_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(default='pending', max_length=50)),
                ('build', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchases', to='builds.build')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchases', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SavedBuild',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saved_at', models.DateTimeField(auto_now_add=True)),
                ('build', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_by_users', to='builds.build')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_builds', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'build')},
            },
        ),
    ]
