# Generated by Django 5.2.5 on 2025-10-02 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builds', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='build',
            name='category',
            field=models.CharField(choices=[('office', 'Office / Study'), ('editing', 'Editing / AI-ML'), ('gaming', 'Gaming & Streaming')], default='office', max_length=20),
        ),
        migrations.AddField(
            model_name='build',
            name='intensity',
            field=models.CharField(choices=[('casual', 'Casual'), ('heavy', 'Heavy')], default='casual', max_length=20),
        ),
    ]
