# Generated by Django 5.2.5 on 2025-10-02 13:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builds', '0002_build_category_build_intensity'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='savedbuild',
            name='build',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_by_users', to='builds.build'),
        ),
        migrations.AlterUniqueTogether(
            name='savedbuild',
            unique_together={('user', 'build')},
        ),
    ]
