# Generated by Django 5.2.5 on 2025-10-07 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('builds', '0003_alter_savedbuild_build_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='component',
            unique_together={('type', 'name', 'specs')},
        ),
    ]
