# Generated by Django 5.2.5 on 2025-10-08 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builds', '0004_alter_component_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='build',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
