# Generated by Django 5.2.5 on 2025-10-09 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builds', '0005_build_is_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='build',
            name='vendor_build_id',
            field=models.IntegerField(blank=True, db_index=True, help_text='Links to VendorBuild.id for sync tracking', null=True),
        ),
    ]
